language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip3 install pyflakes

script:
  - coverage run -m unittest discover
#  - coverage run tests/test_SDTLResult.py tests/test_client.py
  - python3 -m pyflakes
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)