language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip3 install pyflakes

script:
  - pytest --cov=SDTLpy --cov-report=xml tests/
  - python3 -m pyflakes
after_success:
  - bash < (curl -s https://codecov.io/bash)