language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  pytest --cov=codecov
after_success:
  - bash < (curl -s https://codecov.io/bash)
branches:
  only:
    - master